version: "2"
services:
  interfaceserver:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 cardgame_channels.asgi_docker_compose:channel_layer
    depends_on:
      - database
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: 'cardgame_channels.settings_docker_compose'
#    ports:
#      - 8000:8000
    user: app
    working_dir: /app
    volumes:
      - .:/app
    restart: always
  workerserver_1:
    build: .
    command: python manage.py runworker
    depends_on:
      - database
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: 'cardgame_channels.settings_docker_compose'
    working_dir: /app
    user: app
    volumes:
      - .:/app
    restart: always
  workerserver_2:
    build: .
    command: python manage.py runworker
    depends_on:
      - database
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: 'cardgame_channels.settings_docker_compose'
    working_dir: /app
    user: app
    volumes:
      - .:/app
    restart: always
  database:
    image: postgres:9.5
    restart: always
  redis:
    image: redis:3.0-alpine
    restart: always
  nginx:
    image: nginx
    depends_on:
      - database
      - interfaceserver
      - redis
      - workerserver_1
      - workerserver_2
    volumes:
      - .:/app
      - ./devscripts/docker-compose/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8668:80
    restart: always
